server:
  port: 8080

oauth2:
  client:
    clientId: your_client_id
    clientSecret: your_client_secret
    scope: your_scopes
    grantType: your_grant_type
    accessTokenUri: https://auth.tado.com/oauth/token
  
tado:
  api:
    userInfo: https://my.tado.com/api/v2/me
    homeZonesInfo: https://my.tado.com/api/v2/homes/{home_id}/zones
    zoneState: https://my.tado.com/api/v2/homes/{home_id}/zones/{zone_id}/state
    overlay: https://my.tado.com/api/v2/homes/{home_id}/zones/{zone_id}/overlay 
  